modLoader="javafml"
loaderVersion="[45,46)"
license="All rights reserved"
[[mods]]
    modId="survivalreimagined"
    version="${file.jarVersion}"
    displayName="Survival Reimagined"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/iguanatweaks-reborn"
    #logoFile="examplemod.png"
    credits = "Thanks to Iguana for the original Mod. Effect Icons made by hamzaa#1200. Injured sound by thecheeseman from freesound.org. Stamina overlay code from AppleSkin exhaustion code. Tocinin#8975 for the Flint Blocks textures. Carboniglio for Alpha testing and many ideas. kioraSperlusenta for bearing with me in livestream."
    authors = "Insane96MCP"
    description = '''
    Multiple changes to bring back Survival in Minecraft.
    Movement Restrictions, Farming, Mining, Explosions and much more.

    Formerly known as Iguana Tweaks Reborn
    '''
    # Catalogue icon
    # itemIcon = "survivalreimagined:flint_pickaxe"
    # Configured background
    configBackground = "survivalreimagined:textures/block/rich_farmland_moist.png"

[[dependencies.survivalreimagined]]
    modId="forge"
    mandatory=true
    versionRange="[45,46)"
    ordering="NONE"
    side="BOTH"

[[dependencies.survivalreimagined]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.survivalreimagined]]
    modId="insanelib"
    mandatory=true
    versionRange="[1.9.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.survivalreimagined]]
    modId="mobspropertiesrandomness"
    mandatory=true
    versionRange="[4.5.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.survivalreimagined]]
    modId="pehkui"
    mandatory=true
    versionRange="[3.7.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.survivalreimagined]]
    modId="shieldsplus"
    mandatory=true
    versionRange="[1.5.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.survivalreimagined]]
    modId="enhancedai"
    mandatory=true
    versionRange="[1.12.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.survivalreimagined]]
    modId="sereneseasons"
    mandatory=true
    versionRange="[8.3.0.39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.survivalreimagined]]
    modId="passablefoliage"
    mandatory=false
    versionRange="[7.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.survivalreimagined]]
    modId="toolbelt"
    mandatory=false
    versionRange="[1.20.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.survivalreimagined]]
    modId="easymagic"
    mandatory=false
    versionRange="[6.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.survivalreimagined]]
    modId="corail_woodcutter"
    mandatory=false
    versionRange="[2.7.0,)"
    ordering="NONE"
    side="BOTH"
