modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"
[[mods]]
    modId="iguanatweaksexpanded"
    version="${file.jarVersion}"
    displayName="Iguana Tweaks Expanded"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/iguanatweaks-expanded"
    #logoFile="examplemod.png"
    credits = ""
    authors = "Insane96MCP"
    description = '''
        Expand upon IguanaTweaks Reborn, with new items, tools, blocks, enchantments ...
    '''
    # Catalogue icon
    # itemIcon = "iguanatweaksexpanded:flint_pickaxe"
    # Configured background
    configBackground = "iguanatweaksexpanded:textures/block/rich_farmland_moist.png"

[[dependencies.iguanatweaksexpanded]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.iguanatweaksexpanded]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.iguanatweaksexpanded]]
    modId="insanelib"
    mandatory=true
    versionRange="[1.13.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.iguanatweaksexpanded]]
    modId="iguanatweaksreborn"
    mandatory=true
    versionRange="[3.5.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.iguanatweaksexpanded]]
    modId="shieldsplus"
    mandatory=true
    versionRange="[1.8.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.iguanatweaksexpanded]]
    modId="enhancedai"
    mandatory=true
    versionRange="[2.2.2,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.iguanatweaksexpanded]]
    modId="sereneseasons"
    mandatory=true
    versionRange="[9.0.0.46,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.iguanatweaksexpanded]]
    modId="timecontrol"
    mandatory=false
    versionRange="[1.6.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.iguanatweaksexpanded]]
    modId="maxhealthfix"
    mandatory=true
    versionRange="[12.0.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.iguanatweaksexpanded]]
    modId="mobspropertiesrandomness"
    mandatory=false
    versionRange="[4.7.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.iguanatweaksexpanded]]
    modId="pehkui"
    mandatory=false
    versionRange="[3.7.7,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.iguanatweaksexpanded]]
    modId="passablefoliage"
    mandatory=false
    versionRange="[7.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.iguanatweaksexpanded]]
    modId="toolbelt"
    mandatory=false
    versionRange="[1.20.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.iguanatweaksexpanded]]
    modId="sawmill"
    mandatory=false
    versionRange="[1.2.6,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.iguanatweaksexpanded]]
    modId="globaldataandresourcepacks"
    mandatory=false
    versionRange="[1.16.2,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.iguanatweaksexpanded]]
    modId="paxi"
    mandatory=false
    versionRange="[1.20-forge-4.0,)"
    ordering="AFTER"
    side="BOTH"