modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
[[mods]]
    modId="survivalreimagined"
    version="${file.jarVersion}"
    displayName="Survival Reimagined"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/iguanatweaks-reborn"
    #logoFile="examplemod.png"
    credits = "Thanks to Iguana for the original Mod. Effect Icons made by hamzaa#1200. Injured sound by thecheeseman from freesound.org. Stamina overlay code from AppleSkin exhaustion code."
    authors = "Insane96MCP"
    description = '''
    Multiple changes to make Minecraft Harder.
    Movement Restrictions, Farming, Mining, Explosions and much more.

    Formerly known as Iguana Tweaks Reborn
    '''
    # Catalogue icon
    itemIcon = "survivalreimagined:flint_pickaxe"
    # Configured background
    configBackground = "minecraft:textures/block/cobblestone.png"

    [[dependencies.survivalreimagined]]
        modId="forge"
        mandatory=true
        versionRange="[44,)"
        ordering="NONE"
        side="BOTH"

    [[dependencies.survivalreimagined]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.19.3,1.20)"
        ordering="NONE"
        side="BOTH"

    [[dependencies.survivalreimagined]]
        modId="insanelib"
        mandatory=true
        versionRange="[1.8.1,)"
        ordering="NONE"
        side="BOTH"

    [[dependencies.survivalreimagined]]
        modId="mobspropertiesrandomness"
        mandatory=true
        versionRange="[4.3.0,)"
        ordering="NONE"
        side="BOTH"

    [[dependencies.survivalreimagined]]
        modId="shieldsplus"
        mandatory=true
        versionRange="[1.4.1,)"
        ordering="NONE"
        side="BOTH"


    [[dependencies.survivalreimagined]]
        modId="sereneseasons"
        mandatory=true
        versionRange="[8.2.0.37,)"
        ordering="NONE"
        side="BOTH"
